<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">
<head>
<title>MasterGST | All Accounting Details</title>
<script src="${contextPath}/static/mastergst/js/journal/journal.js" type="text/javascript"></script> 
</head>
<body class="body-cls">
<div class="modal fade" id="voucherModal" role="dialog" aria-labelledby="voucherModal" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-right" role="document">
            <div class="modal-content">
				<div class="modal-header p-0">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"> <img src="${contextPath}/static/mastergst/images/master/closeicon-blue.png" alt="Close" /></span>
                    </button>
                    <div class="bluehdr" style="width:100%">
                        <h3>Vouchers</h3>
                    </div>
				</div>
          <div class="modal-body">
                <form:form method="post" data-toggle="validator" class="p-4" name="vocherform" id="vocherform" action="${contextPath}/record_vouchers/${id}/${client.id}/${fullname}/${usertype}/${month}/${year}"  modelAttribute="vouchers">
                <div class="meterialform row mb-4">
                 <div class="form-group col-md-6 col-sm-12 "><p class="lable-txt astrich">Voucher Number</p><span class="errormsg" id="voucherNumber_Msg"></span><input type="text" class="voucherNumbers" id="voucherNumbers55" name="voucherNumber" required="required" data-error="Please enter voucher number"  placeholder="voucher number" /><label for="input" class="control-label"></label><div class="help-block with-errors"></div><i class="bar"></i> </div>
				<div class="form-group col-md-6 col-sm-12 "><p class="lable-txt astrich">Voucher Date</p><input type="text" id="dateofvocher" name="voucherDate" class="form-control date_of_voucher"  aria-describedby="dateofvocher" onkeypress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 43) || (event.charCode == 47) || (event.charCode == 0))" placeholder="DD-MM-YYYY"  required="required" data-error="Please enter valid date"/><label for="input" class="control-label"></label><div class="help-block with-errors"></div><i class="bar"></i></div>
				<div class="form-group col-md-6 col-sm-12 "><p class="lable-txt">Voucher Type</p><input type="text" class="form-control" id="voucherNumbersType" name="vouchertype" placeholder="voucher type" /><label for="input" class="control-label"></label><div class="help-block with-errors"></div><i class="bar"></i> </div>			
				</div>
				<span class="errormsg" id="vouchererrormsg" style="height:18px"></span>
				<table align="center" id="vsortable_table4" border="0" class="row-border dataTable voucher_table" style="margin-bottom: 9%;width: 750px;">
              <thead><tr><th style="width:5%">S.No</th><th style="width:14%">Dr / Cr</th><th style="width:46%">Ledger Name</th><th style="width:15%">Dr Amount </th><th style="width:15%">Cr Amount</th><th style="width:4%"></th></tr></thead>
              <tbody id="voucherbody">
                <tr id="1" class=""><td id="sno_row2" align="center">1</td><td id="" class="form-group" style="border: none;margin-bottom: 0px;"><select class="form-control mov_text1" id="voucher_mode1" name="voucheritems[0].modeOfVoucher" onChange="drcrType(1,'voucher')" id="mov" required="required" data-error="Please select Voucher type"><option value="">-Select-</option><option value="Dr">Dr</option><option value="Cr">Cr</option></select></td><td class="form-group"><input type="text" class="form-control ledger_text1"  required="required"  placeholder="Ledger" id="voucherledger_text1" name="voucheritems[0].ledger"/><div id="addvoucherlegername" style="display:none"><div class="vledgerddbox"><p id="newledger">Please add new Ledger</p><input type="button" class="btn btn-sm btn-blue-dark" id="newledgerval" value="Add New Ledger" data-toggle="modal" onclick="addLedger('1','voucher','addLedgerModal')" ></div></div></td><td id="dramttd" class="form-group"><input type="text" class="form-control amount_check voucherdramount voucherdramt_text1" id="voucherdramt_text1" name="voucheritems[0].dramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(1,'voucher')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td id="cramttd" class="form-group"><input type="text" class="form-control amount_check vouchercramount vouchercramt_text1" id="vouchercramt_text1" name="voucheritems[0].cramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(1,'voucher')" onKeyUp="" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td align="center" width="2%" style="text-align:center;"><a href="javascript:void(0)" id="delete_button1" class="item_delete" onclick="delete_Accrow(1,'voucher')"> <span class="fa fa-trash-o gstr2adeletefield"></span> </a> </td></tr>
                 <tr id="2" class=""><td id="sno_row3" align="center">2</td><td id="" class="form-group" style="border: none;margin-bottom: 0px;"><select class="form-control mov_text2" id="voucher_mode2" name="voucheritems[1].modeOfVoucher" onChange="drcrType(2,'voucher')" id="mov" required="required" data-error="Please select Voucher type"><option value="">-Select-</option><option value="Dr">Dr</option><option value="Cr">Cr</option></select></td><td class="form-group"><input type="text" class="form-control ledger_text2"  required="required"  placeholder="Ledger" id="voucherledger_text2" name="voucheritems[1].ledger"/><div id="addvoucherlegername2" style="display:none"><div class="vledgerddbox"><p id="newledger2">Please add new Ledger</p><input type="button" class="btn btn-sm btn-blue-dark" id="newledgerval2" value="Add New Ledger" data-toggle="modal" onclick="addLedger('2','voucher','addLedgerModal')" ></div></div></td><td id="dramttd2" class="form-group"><input type="text" class="form-control amount_check voucherdramount voucherdramt_text2" id="voucherdramt_text2" name="voucheritems[1].dramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(2,'voucher')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td id="cramttd" class="form-group"><input type="text" class="form-control amount_check vouchercramount vouchercramt_text2" id="vouchercramt_text2" name="voucheritems[1].cramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(2,'voucher')" onKeyUp="" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td align="center" width="2%" style="text-align:center;"><a href="javascript:void(0)" id="delete_button2" class="item_delete" onclick="delete_Accrow(2,'voucher')"> <span class="fa fa-trash-o gstr2adeletefield"></span> </a> </td></tr>
              </tbody>
              <tfoot style="color:black"><th colspan="2" class="text-left"><i class="add-btn" onclick="addAccountingrow('voucher')" style="cursor: pointer;">+</i><span style="color:black">Add Another Row</span></th><th style="color:black">Subtotal</th><th id="voucherdrtot" style="color:black">0.00</th><th id="vouchercrtot" style="color:black">0.00</th><th colspan="1" style="text-align: right;"><i class="add-btn"  onclick="addAccountingrow('voucher')" style="cursor: pointer;">+</i></th></tfoot>
            </table>
            <div class="form-group mb-2" id="" style=""><label for="inlineFormInput" class="bold-txt">Notes</label><textarea class="form-control mb-2 mr-sm-2 mb-sm-0" id="voucher_notes" style="min-height: 80px !important; margin-top: 0px; margin-bottom: 0px;" name="vouchernotes">Voucher Notes</textarea>		            	<input type="hidden" name="actiontype" id="voucherActiontype"/></div>
				 <input type="hidden" id="userId" name="userId" value="<c:out value="${id}"/>"><input type="hidden" id="clientId" name="clientId" value="<c:out value="${client.id}"/>"><input type="hidden" id="voucherdramounthidden" name="totdramount" value=""><input type="hidden" id="vouchercramounthidden" name="totcramount" value=""><div class=" style="position: absolute;bottom: 0px;right:0px"><button class="btn btn-blue-dark addvou_submit" style="display:none">Add Voucher</button>
			</div>  
 </form:form>
  
  </div>
 <div class="modal-footer text-center" style="display:block">
	<label for="addvou_submit" class="btn btn-blue-dark m-0" id="addVoucherbtn" tabindex="0" onClick="addvcInvoices('Voucher')">Add Voucher</label>
	<a href="#" class="btn btn-blue-dark ml-2" data-dismiss="modal" aria-label="Close" onClick="closevcmodal()">Cancel</a> 
  </div>
  </div>
</div>
</div>
<div class="modal fade" id="ContraModal" role="dialog" aria-labelledby="ContraModal" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-right" role="document">
            <div class="modal-content">
      <div class="modal-body">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close" onClick="closevcmodal()"><span aria-hidden="true"> <img src="${contextPath}/static/mastergst/images/master/closeicon-blue.png" alt="Close" /></span></button>
                    <div class="invoice-hdr bluehdr"><h3>Contra</h3></div>
                <form:form method="post" data-toggle="validator" class="p-4" name="contraform" id="contraform" action="${contextPath}/record_contra/${id}/${client.id}/${fullname}/${usertype}/${month}/${year}"  modelAttribute="contra">
                <div class="meterialform row mb-4">
                 <div class="form-group col-md-6 col-sm-12 "><p class="lable-txt astrich">Contra Number</p><span class="errormsg" id="voucherNumber_Msg"></span><input type="text" class="contraNumbers" id="contraNumbers" name="contraNumber" required="required" data-error="Please enter contra number"  placeholder="contra number" /><label for="input" class="control-label"></label><div class="help-block with-errors"></div><i class="bar"></i> </div>
				<div class="form-group col-md-6 col-sm-12 "><p class="lable-txt astrich">Contra Date</p><input type="text" id="dateofcontra" name="contraDate" class="form-control date_of_contra" aria-describedby="dateofcontra" onkeypress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 43) || (event.charCode == 47) || (event.charCode == 0))" placeholder="DD-MM-YYYY"  required="required" data-error="Please enter valid date"/><label for="input" class="control-label"></label><div class="help-block with-errors"></div><i class="bar"></i></div>			
				</div>
				<span class="errormsg" id="contraerrormsg" style="height:18px"></span>
				<table align="center" id="vsortable_table5" border="0" class="row-border dataTable contra_table" style="margin-bottom: 9%;width:750px;">
              <thead><tr><th style="width:5%">S.No</th><th style="width:14%">Dr / Cr</th><th style="width:46%">Ledger Name</th><th style="width:15%">Dr Amount </th><th style="width:15%">Cr Amount</th><th style="width:4%"></th></tr></thead>
              <tbody id="contrabody">
                <tr id="1" class=""><td id="sno_row2" align="center">1</td><td id="" class="form-group" style="border: none;margin-bottom: 0px;"><select class="form-control mov_text1" id="contra_mode1" name="contraitems[0].modeOfVoucher" onChange="drcrType(1,'contra')" id="mov" required="required" data-error="Please select contra type"><option value="">-Select-</option><option value="Dr">Dr</option><option value="Cr">Cr</option></select></td><td class="form-group"><input type="text" class="form-control contraledger_text1" id="contraledger_text1" required placeholder="Ledger" name="contraitems[0].ledger"/><div id="addcontralegername1" style="display:none"><div class="vledgerddbox"><p id="newledger">Please add new Ledger</p><input type="button" class="btn btn-sm btn-blue-dark" id="newledgerval" value="Add New Ledger" data-toggle="modal" onclick="addLedger('1','contra','addLedgerModal')" ></div></div></td><td id="contradramttd" class="form-group"><input type="text" class="form-control contradramount contradramt_text1" id="contradramt_text1" name="contraitems[0].dramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(1,'contra')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td id="contracramttd" class="form-group"><input type="text" class="form-control contracramount contracramt_text1" id="contracramt_text1" name="contraitems[0].cramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(1,'contra')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td align="center" width="2%" style="text-align:center;"><a href="javascript:void(0)" id="delete_button1" class="item_delete" onclick="delete_Accrow(1,'contra')"> <span class="fa fa-trash-o gstr2adeletefield"></span> </a> </td></tr>
                 <tr id="2" class=""><td id="sno_row3" align="center">2</td><td id="" class="form-group" style="border: none;margin-bottom: 0px;"><select class="form-control mov_text2" id="contra_mode2" name="contraitems[1].modeOfVoucher" onChange="drcrType(2,'contra')" id="mov" required="required" data-error="Please select contra type"><option value="">-Select-</option><option value="Dr">Dr</option><option value="Cr">Cr</option></select></td><td class="form-group"><input type="text" class="form-control contraledger_text2" id="contraledger_text2" required placeholder="Ledger" name="contraitems[1].ledger"/><div id="addcontralegername2" style="display:none"><div class="vledgerddbox"><p id="newledger2">Please add new Ledger</p><input type="button" class="btn btn-sm btn-blue-dark" id="newledgerval2" value="Add New Ledger" data-toggle="modal" onclick="addLedger('2','contra','addLedgerModal')" ></div></div></td><td id="contradramttd2" class="form-group"><input type="text" class="form-control contradramount contradramt_text2" id="contradramt_text2" name="contraitems[1].dramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(2,'contra')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td id="contracramttd" class="form-group"><input type="text" class="form-control contracramount contracramt_text2" id="contracramt_text2" name="contraitems[1].cramount" required="required" pattern="[0-9]+(\.[0-9][0-9]?)?" data-error="Please enter amount" onKeyUp="findtotal(2,'contra')" onKeyPress="return ((event.charCode >= 48 && event.charCode <= 57) || (event.charCode == 46) || (event.charCode == 8))" placeholder="Amount" /></td><td align="center" width="2%" style="text-align:center;"><a href="javascript:void(0)" id="delete_button2" class="item_delete" onclick="delete_Accrow(2,'contra')"> <span class="fa fa-trash-o gstr2adeletefield"></span> </a> </td></tr>
              </tbody>
             <tfoot style="color:black"><th colspan="2" class="text-left"><i class="add-btn" onclick="addAccountingrow('contra')" style="cursor: pointer;">+</i><span style="color:black">Add Another Row</span></th><th style="color:black">Subtotal</th><th id="contradrtot" style="color:black">0.00</th><th id="contracrtot" style="color:black">0.00</th><th colspan="1" style="text-align: right;"><i class="add-btn"  onclick="addAccountingrow('contra')" style="cursor: pointer;">+</i></th></tfoot>
            </table>
            <div class="form-group mb-2" id="" style=""><label for="inlineFormInput" class="bold-txt">Notes</label><textarea class="form-control mb-2 mr-sm-2 mb-sm-0" id="contra_notes" style="min-height: 80px !important; margin-top: 0px; margin-bottom: 0px;" name="contranotes">Contra Notes</textarea><input type="hidden" name="actiontype" id="contraActiontype"/></div>
				 <input type="hidden" id="userId" name="userId" value="<c:out value="${id}"/>"><input type="hidden" id="clientId" name="clientId" value="<c:out value="${client.id}"/>"><input type="hidden" id="contradramounthidden" name="totdramount" value=""><input type="hidden" id="contracramounthidden" name="totcramount" value="">
				 <div class="modal-footer" style="position: absolute;bottom: 0px;right:0px">
        <input class="btn btn-blue-dark addcontra_submit"  style="display:none" value="Add Contra">
      </div>  
 </form:form>
  </div>
  <div class="modal-footer text-center" style="display:block">
	<label for="addcontra_submit" class="btn btn-blue-dark m-0" id="addContrabtn" tabindex="0" onClick="addvcInvoices('Contra')">Add Contra</label>
	<a href="#" class="btn btn-blue-dark ml-2" data-dismiss="modal" aria-label="Close" onClick="closevcmodal()">Cancel</a> 
  </div>
  </div>
</div>
</div>  
</body>
</html>